postgresql:
  restart: always
  image: sameersbn/postgresql:9.4-11
  environment:
    - DB_USER=gitlab
    - DB_PASS=chachacha
    - DB_NAME=gitlabhq_production
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql
gitlab:
  restart: always
  image: sameersbn/gitlab:8.3.2
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - DEBUG=false
    - TZ=Europe/Madrid
    - GITLAB_TIMEZONE=Madrid

    - GITLAB_SECRETS_DB_KEY_BASE=chachacha

    - GITLAB_HOST=lsi.vc.ehu.es
    - GITLAB_PORT=80
    - GITLAB_SSH_PORT=80
    - GITLAB_RELATIVE_URL_ROOT=/gitlab
    - GITLAB_HTTPS=false
    - SSL_SELF_SIGNED=true

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=pablo.gonzalez@ehu.eus
    - GITLAB_EMAIL_REPLY_TO=noreply@lsi.vc.ehu.es
    - GITLAB_INCOMING_EMAIL_ADDRESS=noreply@ehu.eus

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=true
    - SMTP_DOMAIN=ehu.es
    - SMTP_HOST=smtp.ehu.es
    - SMTP_PORT=25
    - SMTP_STARTTLS=false
    - SMTP_AUTHENTICATION=none

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
redis:
  restart: always
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis

