Vagrant.configure("2") do |config|

	# Specify the base box
	config.vm.box = "ubuntu/xenial64"

	# Setup port forwarding
	config.vm.network :forwarded_port, guest: 10080, host: 8931, auto_correct: true

    # Setup synced folder
    config.vm.synced_folder "./", "/var/www", create: true, group: "www-data", owner: "www-data"

    # VM specific configs
    config.vm.provider "virtualbox" do |v|
    	v.name = "Test Vagrant Docker"
    	v.customize ["modifyvm", :id, "--memory", "2048"]
    end

    # Shell provisioning
    config.vm.provision "shell" do |s|
    	s.path = "provision/setup.sh"
    end
end
